//todo:
Spec List | Failures
ContactComponent should create
Failed: Template parse errors:
Can't bind to 'formGroup' since it isn't a known property of 'form'. ("<h1>Contact us</h1>

<form [ERROR ->][formGroup]="messageForm" (ngSubmit)="onSubmit()">

  <h5 *ngIf="success">Your form is valid!</h5>
"): ng:///DynamicTestModule/ContactComponent.html@2:6
Error: Template parse errors:
Can't bind to 'formGroup' since it isn't a known property of 'form'. ("<h1>Contact us</h1>

<form [ERROR ->][formGroup]="messageForm" (ngSubmit)="onSubmit()">